"""Add profile_pic to User

Revision ID: e5696fa11e93
Revises: 
Create Date: 2025-07-28 09:37:53.152915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5696fa11e93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('borrower', schema=None) as batch_op:
        batch_op.drop_column('loan')

    # ### end Alembic commands ###
